package org.example.enums;

public enum EUniversityMethodComparator {
    UNIVERSITY_FULL_NAME_COMPARATOR,
    UNIVERSITY_SHORT_NAME_COMPARATOR,
    UNIVERSITY_ID_COMPARATOR,
    UNIVERSITY_MAIN_PROFILE_COMPARATOR,
    UNIVERSITY_YEAR_OF_FOUNDATION_COMPARATOR

}
